INSERT INTO blogful_articles (title, content, date_published)
VALUES 
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Fish tricks', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL),
    ('Not Dogs', 'fgdfgdfg', now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 'Habitant elementum massa blandit.', now() - '21 days'::INTERVAL)
    
